apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-pv
spec:
  storageClassName: web-image-pv # the name of the volume used to claim this volume
  capacity:
    storage: 1Gi
  volumeMode: Filesystem # the volume will be mounted into pods as a directory
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/kube # the volume uses path in a cluster node as a storage

  nodeAffinity: # only required for local, defines which nodes can access the volume
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0
